import { IMAGES, IMAGES_META, ICONS, ICONS_META } from "@/assets/images";

import type { SolutionIndustriesContent } from "@/types/solutions";

export const WEBSITE_DESIGN_SERVICE_HERO = {
  title: "Website Design Services for the AI Era — Across Industries",
  description: "Our website design services combine strategy, UX/UI design, brand expression, content architecture, performance thinking, accessibility and AI-era digital experience design to create websites that do more than look modern—they help organizations communicate, compete and convert.",
  description2: "In the AI era, a website is no longer simply a digital brochure. It is a brand interface, search and answer-engine destination, product discovery layer, content system, conversion engine and increasingly an intelligent gateway to services, data and AI-assisted experiences. Obrive designs websites for startups, SMEs and enterprises with a focus on clarity, trust, responsive experiences, scalable content systems, measurable journeys and future-ready foundations. Our work can extend from corporate websites and landing pages to eCommerce, portals, knowledge hubs, campaign experiences and AI-enabled digital platforms.",
  ctaButtons: { primary: "Explore Solutions", secondary: "SCHEDULE A DEMO" },
};

export const WEBSITE_DESIGN_SERVICE_KEY_BENEFITS = [
  { title: "Design a Website That Works in the AI Era", description: "Your website must now serve more than human visitors. It must communicate clearly to search engines, answer engines, AI assistants, social discovery systems and the people who ultimately make decisions. Obrive creates digital experiences structured around people-first usability and machine-readable clarity—so your brand, expertise, products and services are easier to discover, understand and act upon.", src: ICONS.BOX_CHECK_ICON, srcMeta: ICONS_META.BOX_CHECK_ICON },
  { title: "Business-First Website Strategy", description: "We start with business goals, audiences, positioning, competitors, conversion paths, content, technology constraints and measurable outcomes before defining the visual direction. The goal is to make design serve the business—not design for decoration.", src: ICONS.BOX_CHECK_ICON, srcMeta: ICONS_META.BOX_CHECK_ICON },
  { title: "Human-Centered UX & Conversion Design", description: "We design information architecture, navigation, interaction patterns, page hierarchy, forms, calls to action and responsive layouts around how users actually discover, evaluate and choose.", src: ICONS.BOX_CHECK_ICON, srcMeta: ICONS_META.BOX_CHECK_ICON },
  { title: "AI-Ready Information Architecture", description: "AI-era websites need structured information. We organize content into clear entities, topics, services, products, FAQs and relationships that can support search visibility, answer-engine understanding, internal search and future AI experiences.", src: ICONS.BOX_CHECK_ICON, srcMeta: ICONS_META.BOX_CHECK_ICON },
  { title: "Content-Led Visual Design", description: "Design and content work together. We create layouts that give important messages, proof, expertise, product information, case studies and calls to action the right visual priority.", src: ICONS.BOX_CHECK_ICON, srcMeta: ICONS_META.BOX_CHECK_ICON },
  { title: "Performance, Accessibility & Responsive Experience", description: "We design for mobile-first responsiveness, efficient visual systems, accessible interaction, readable content, fast-loading experiences and practical performance requirements across modern devices.", src: ICONS.BOX_CHECK_ICON, srcMeta: ICONS_META.BOX_CHECK_ICON },
];

export const WEBSITE_DESIGN_SERVICE_SIDEBAR_LINKS = [
  { id: "our-services", label: "Our Services" },
  { id: "global-website-design-delivery", label: "Global Website Design Delivery" },
  { id: "what-makes-a-website-design-project-successful", label: "What Makes a Website Design Project Successful?" },
  { id: "why-choose-obrive-for-website-design", label: "Why Choose Obrive for Website Design?" },
  { id: "business-outcomes-website-design-can-support", label: "Business Outcomes Website Design Can Support" },
] as const;

export const WEBSITE_DESIGN_SERVICE_SERVICE_SECTIONS = [
  {
    id: "our-services",
    title: "Our Services",
    subtitle: "",
    description: "",
    label: "",
    items: [],
    subSections: [
      {
        title: "Enterprise Integration",
        description: "Web experiences can connect with CMS platforms, CRM, ERP, commerce systems, analytics, marketing automation, APIs, customer portals, AI services and other business systems as required.",
      },
      {
        title: "Corporate Website Design",
        description: "Create a credible, modern digital presence that clearly communicates your organization, capabilities, differentiation, proof and next action.",
        items: [
          "Corporate websites",
          "Company websites",
          "Enterprise websites",
          "Investor and stakeholder pages",
          "Leadership and company profiles",
          "Global/localized websites",
          "Reputation and trust experiences",
        ],
      },
      {
        title: "UI/UX Website Design",
        description: "Design intuitive interfaces that reduce friction and help users find information, understand value and complete important actions.",
        items: [
          "Information architecture",
          "Wireframes",
          "Responsive UI systems",
          "Navigation design",
          "Conversion journeys",
          "Design systems",
          "Accessibility-aware interfaces",
          "Interaction design",
          "Usability validation",
        ],
      },
      {
        title: "AI-Ready Website Design",
        description: "Design websites for a world where users discover information through Google, AI assistants, answer engines and conversational interfaces.",
        items: [
          "Answer-first content structures",
          "Entity-led information architecture",
          "FAQ and knowledge patterns",
          "Structured content layouts",
          "AI-assisted discovery journeys",
          "Conversational entry points",
          "Machine-readable content strategy",
          "Human + AI discovery experiences",
        ],
      },
      {
        title: "Website Redesign & Digital Transformation",
        description: "Modernize outdated websites without losing valuable content, search equity or brand recognition. Rebuild the experience around current user expectations and business priorities.",
        items: [
          "UX audit",
          "Information architecture redesign",
          "Visual redesign",
          "Content restructuring",
          "Migration planning",
          "Responsive modernization",
          "Conversion optimization",
          "Technical handoff",
        ],
      },
      {
        title: "eCommerce Website Design",
        description: "Design product discovery and commerce journeys that make browsing, comparison, confidence and checkout easier.",
        items: [
          "Storefront design",
          "Product detail pages",
          "Category experiences",
          "Search and filtering",
          "Product comparison",
          "Cart and checkout UX",
          "Personalized discovery",
          "Commerce integrations",
        ],
      },
      {
        title: "Landing Page & Campaign Design",
        description: "Build focused digital experiences for launches, campaigns, lead generation, events, products and high-intent traffic.",
        items: [
          "Campaign landing pages",
          "Lead-generation pages",
          "Product launches",
          "Event pages",
          "Paid-traffic landing experiences",
          "A/B-test-ready variants",
          "Interactive storytelling",
        ],
      },
      {
        title: "Web Portal & Customer Experience Design",
        description: "Design authenticated or self-service web experiences that organize complex information and workflows.",
        items: [
          "Customer portals",
          "Partner portals",
          "Employee portals",
          "Service dashboards",
          "Knowledge centers",
          "Account experiences",
          "Self-service journeys",
        ],
      },
      {
        title: "3D, Motion & Interactive Web Design",
        description: "Use motion, 3D and interactive storytelling where they improve understanding or engagement without compromising usability or performance.",
        items: [
          "3D product experiences",
          "Motion systems",
          "Scroll storytelling",
          "Interactive product views",
          "Micro-interactions",
          "WebGL experiences",
          "Immersive landing pages",
        ],
      },
      {
        title: "AI-Powered Website Experiences",
        description: "Design interfaces that can connect users with AI assistants, recommendation systems, knowledge retrieval or workflow automation where the use case supports it.",
        items: [
          "AI assistants",
          "Conversational interfaces",
          "AI search",
          "Knowledge retrieval",
          "Recommendation experiences",
          "Personalized content",
          "AI lead qualification",
          "Workflow automation interfaces",
        ],
      },
      {
        title: "SEO, AEO & GEO Experience Design",
        description: "Design pages so information is clear for people and structured for modern discovery across search engines, answer engines and generative interfaces.",
        items: [
          "Search-intent architecture",
          "Answer-first sections",
          "FAQ design",
          "Topic clusters",
          "Internal-linking UX",
          "Entity and service structure",
          "Snippet-friendly layouts",
          "Content discoverability",
        ],
      },
      {
        title: "Website Design Systems & Brand Experience",
        description: "Create reusable visual and interaction systems that keep large websites consistent while allowing teams to scale content and pages.",
        items: [
          "Design systems",
          "Component libraries",
          "Typography systems",
          "Spacing and layout rules",
          "Reusable sections",
          "Brand governance",
          "Multi-page consistency",
          "Developer-ready specifications",
        ],
      },
      {
        title: "Website Analytics & Continuous Optimization",
        description: "Design the website as an evolving product, using measurable user behavior and business outcomes to guide improvements.",
        items: [
          "Conversion tracking plans",
          "Engagement analysis",
          "Funnel thinking",
          "Experiment-ready layouts",
          "Content performance reviews",
          "UX improvement roadmaps",
        ],
      },
    ],
    footer: "",
  },
  {
    id: "global-website-design-delivery",
    title: "Global Website Design Delivery",
    subtitle: "",
    description: "Build Once. Scale Across Markets. Obrive can structure websites for multiple markets, audiences, languages, product lines and business units while maintaining a consistent design system and content architecture. Choose the Stack That Fits the Business. Website design should be platform-aware without being platform-dependent. We design experiences that can be implemented across modern CMS, headless, custom and web-application architectures.",
    label: "",
    items: [
      "Multi-language and localization-ready structures",
      "Responsive design across modern devices",
      "Reusable component systems",
      "Global navigation and content models",
      "Role-based enterprise experiences",
      "Scalable CMS/content architecture",
      "Analytics and measurement planning",
      "Accessibility-aware design",
      "SEO/AEO/GEO-ready information architecture",
      "Website Design Technology & Platform Capabilities",
      "Modern responsive web design",
      "Design systems and component libraries",
      "CMS and headless CMS experiences",
      "eCommerce UX",
      "Web application interfaces",
      "API-connected experiences",
      "Analytics and measurement",
      "AI and conversational interfaces",
      "3D/WebGL and interactive experiences where appropriate",
      "Performance and accessibility considerations",
      "Developer-ready design specifications",
    ],
    footer: "",
  },
  {
    id: "what-makes-a-website-design-project-successful",
    title: "What Makes a Website Design Project Successful?",
    subtitle: "",
    description: "",
    label: "",
    items: [
      "A clear business objective",
      "Defined audiences and user journeys",
      "Strong information architecture",
      "Clear positioning and messaging",
      "Fast and responsive experience",
      "Accessible and readable interfaces",
      "Consistent design system",
      "Content structured for human and machine discovery",
      "Strong conversion paths",
      "Analytics tied to business outcomes",
      "Maintainable CMS/content architecture",
      "Roadmap for continuous improvement",
    ],
    footer: "",
  },
  {
    id: "why-choose-obrive-for-website-design",
    title: "Why Choose Obrive for Website Design?",
    subtitle: "",
    description: "Obrive brings website strategy, UX/UI, branding, content structure, web technology, AI-era discovery thinking and digital product engineering into one delivery approach.",
    label: "",
    items: [
      "From Digital Presence to AI-Ready Business Experience",
      "Business-first website strategy",
      "Human-centered UX/UI",
      "AI-ready information architecture",
      "SEO/AEO/GEO-aware experience design",
      "Responsive and accessible design",
      "Design systems and scalable components",
      "Corporate, eCommerce and portal experiences",
      "AI-enabled digital experiences",
      "3D and interactive web experiences",
      "Enterprise integrations",
      "Prototype-to-production delivery",
      "Continuous optimization mindset",
    ],
    footer: "",
  },
  {
    id: "business-outcomes-website-design-can-support",
    title: "Business Outcomes Website Design Can Support",
    subtitle: "",
    description: "Results depend on the business, market, content, implementation and ongoing optimization. We recommend defining measurable KPIs before launch. A modern website should be designed as an evolving digital product. Start with a focused business objective, validate the information architecture and experience, launch with measurable foundations, and expand into richer content, personalization, AI, commerce, portals or connected services as the organization grows.",
    label: "",
    items: [
      "Increase clarity and trust",
      "Improve product and service discovery",
      "Create stronger digital differentiation",
      "Reduce user friction",
      "Improve lead-generation journeys",
      "Support eCommerce conversion",
      "Make complex information easier to understand",
      "Strengthen search and answer-engine discoverability",
      "Create a consistent global brand experience",
      "Prepare the website for AI-assisted discovery and interaction",
      "Provide a scalable foundation for future digital products",
      "From Website Redesign to AI-Ready Digital Platform",
    ],
    footer: "",
  },
];

export const WEBSITE_DESIGN_SERVICE_PROCESS_STEPS = [
  { step: "01", title: "Discover", description: "Understand business objectives, audiences, competitors, content, technology, analytics and success criteria." },
  { step: "02", title: "Define", description: "Establish positioning, information architecture, content priorities, user journeys, conversion goals and design direction." },
  { step: "03", title: "Research", description: "Study users, search intent, existing behavior, market expectations and relevant content opportunities." },
  { step: "04", title: "Wireframe", description: "Build page structures and journeys before visual styling." },
  { step: "05", title: "Design", description: "Create the visual system, responsive interfaces, components, interactions and content hierarchy." },
  { step: "06", title: "Prototype", description: "Validate key journeys, interactions and responsive behavior before development." },
  { step: "07", title: "Develop", description: "Implement the approved design with the selected web architecture and content system." },
  { step: "08", title: "Integrate", description: "Connect CMS, CRM, ERP, commerce, analytics, APIs, AI services and other required systems." },
  { step: "09", title: "Test", description: "Validate usability, responsiveness, accessibility, content, performance and key conversion journeys." },
  { step: "10", title: "Launch", description: "Release with appropriate analytics, SEO foundations, redirects, metadata and operational controls." },
  { step: "11", title: "Measure & Improve", description: "Review behavior, search performance, conversion signals and feedback, then continuously improve." },
];

export const WEBSITE_DESIGN_SERVICE_INDUSTRIES = [
  {
    id: "automotive-mobility",
    title: "Automotive & Mobility",
    description: "Corporate websites, product configurators, vehicle discovery, dealer experiences, service portals and AI-assisted customer journeys.",
  },
  {
    id: "manufacturing-industrial-engineering",
    title: "Manufacturing & Industrial Engineering",
    description: "Product and capability sites, technical knowledge hubs, distributor portals, customer self-service and AI-powered documentation experiences.",
  },
  {
    id: "healthcare-medical",
    title: "Healthcare & Medical",
    description: "Healthcare service websites, patient education platforms, provider portals and accessible digital experiences designed around privacy, safety and applicable regulatory requirements.",
  },
  {
    id: "pharmaceuticals-life-sciences",
    title: "Pharmaceuticals & Life Sciences",
    description: "Scientific content platforms, product information hubs, medical education portals and secure stakeholder experiences.",
  },
  {
    id: "retail-ecommerce",
    title: "Retail & eCommerce",
    description: "High-conversion storefronts, product discovery, personalized journeys, commerce integrations, content-rich category experiences and AI-assisted shopping.",
  },
  {
    id: "consumer-goods-brands",
    title: "Consumer Goods & Brands",
    description: "Brand websites, campaign microsites, product storytelling, content hubs, loyalty experiences and interactive product discovery.",
  },
  {
    id: "real-estate-property",
    title: "Real Estate & Property",
    description: "Property discovery platforms, project websites, interactive floor plans, location experiences, lead journeys, virtual tours and developer portals.",
  },
  {
    id: "architecture-engineering-construction",
    title: "Architecture, Engineering & Construction",
    description: "Project portfolios, technical content platforms, BIM/3D-linked experiences, project portals, stakeholder dashboards and bid-support websites.",
  },
  {
    id: "education-edtech",
    title: "Education & EdTech",
    description: "Institution websites, admissions journeys, learning portals, course discovery, student resources and AI-assisted knowledge experiences.",
  },
  {
    id: "energy-utilities-infrastructure",
    title: "Energy, Utilities & Infrastructure",
    description: "Service portals, asset information hubs, customer self-service, project websites, reporting dashboards and technical knowledge centers.",
  },
  {
    id: "oil-gas",
    title: "Oil & Gas",
    description: "Corporate websites, technical knowledge platforms, project communications, recruitment experiences and stakeholder portals.",
  },
  {
    id: "mining-natural-resources",
    title: "Mining & Natural Resources",
    description: "Corporate and project websites, investor information, operational knowledge hubs, recruitment and sustainability communication.",
  },
  {
    id: "aerospace-aviation",
    title: "Aerospace & Aviation",
    description: "Corporate and engineering websites, technical content, supplier portals, recruitment experiences and interactive product storytelling.",
  },
  {
    id: "logistics-warehousing-supply-chain",
    title: "Logistics, Warehousing & Supply Chain",
    description: "Shipment experiences, service portals, customer dashboards, network information, quote journeys and operational knowledge platforms.",
  },
  {
    id: "travel-tourism-hospitality",
    title: "Travel, Tourism & Hospitality",
    description: "Destination websites, hotel experiences, booking journeys, personalized discovery, interactive itineraries and conversational assistance.",
  },
  {
    id: "media-entertainment-gaming",
    title: "Media, Entertainment & Gaming",
    description: "Content-rich websites, media discovery, fan experiences, event platforms, interactive storytelling and personalized content journeys.",
  },
  {
    id: "sports-fitness",
    title: "Sports & Fitness",
    description: "Club and athlete websites, fan engagement, memberships, ticketing journeys, training content and personalized experiences.",
  },
  {
    id: "banking-financial-services-insurance",
    title: "Banking, Financial Services & Insurance",
    description: "Secure service experiences, product discovery, calculators, education hubs, lead journeys and AI-assisted customer support interfaces.",
  },
  {
    id: "telecommunications",
    title: "Telecommunications",
    description: "Plan discovery, device journeys, service portals, support experiences, network information and conversational self-service.",
  },
  {
    id: "agriculture-agritech",
    title: "Agriculture & AgriTech",
    description: "Product and solution websites, knowledge hubs, equipment discovery, farmer resources and field-focused digital journeys.",
  },
  {
    id: "government-public-sector",
    title: "Government & Public Sector",
    description: "Citizen service portals, information architecture, accessibility-focused websites, digital forms, public information and AI-assisted navigation.",
  },
  {
    id: "corporate-learning-professional-services",
    title: "Corporate Learning & Professional Services",
    description: "Expertise websites, resource hubs, service discovery, knowledge portals, lead-generation journeys and AI-assisted content experiences.",
  },
];

export const WEBSITE_DESIGN_SERVICE_INDUSTRIES_CONTENT: SolutionIndustriesContent = {
  slug: "website-design-service",
  hero: {
    title: "Website Design Services Across Industries — AI-Era Industry Solutions",
    description: "Obrive designs industry-specific websites that combine business strategy, user experience, brand communication, structured content and AI-era discoverability. Each experience is shaped around how customers, employees, partners and decision-makers discover and evaluate information.",
  },
  industries: WEBSITE_DESIGN_SERVICE_INDUSTRIES,
  extraBlocks: [
    {
      id: "ai-era-website-design-across-industries",
      title: "AI-Era Website Design Across Industries",
      subtitle: "",
      description: "Across industries, the website increasingly acts as a discovery and decision layer shared by people, search engines, answer engines and AI assistants. Obrive structures content so important information is clear, contextual, reusable and easier to understand.",
      label: "",
      items: ["Entity- and topic-led information architecture", "Answer-first content patterns", "FAQ and knowledge structures", "Structured product/service information", "Internal linking and contextual discovery", "AI-assisted search and conversational entry points", "Accessible human-centered interfaces", "Scalable design systems"],
      footer: "",
    },
  ],
  globalDelivery: {
    title: "Global Website Design Delivery",
    subtitle: "",
    description: "Obrive can support multi-market websites with reusable components, localization-ready content structures, scalable navigation, analytics and governance.",
    items: ["Multi-language experiences", "Regional content variations", "Global design systems", "CMS/content architecture", "Accessibility-aware interfaces", "Analytics and measurement"],
  },
  footerText: "",
};
